on: [push, pull_request]

name: CI

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        run: |
          curl -L https://github.com/kritzcreek/vessel/releases/latest/download/vessel-linux64 --output vessel
          chmod +x vessel

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: vessel verify
        run: |
          ./vessel verify
